# Generated by Django 2.2.6 on 2021-02-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210216_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
    ]
