# Generated by Django 2.2.6 on 2021-02-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_post_delete_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
    ]
