# Generated by Django 2.2.6 on 2021-02-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_post_delete_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='delete_flag',
        ),
    ]
